apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: image: 574349219641.dkr.ecr.us-east-1.amazonaws.com/auth-service:3aca4df...
          ports:
            - containerPort: 8080
