apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: auth-service
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rcrrocha/togglemaster-gitops.git
    targetRevision: main
    path: apps/auth

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
